import { ConfigService } from '@nestjs/config';
import { ForbiddenException, Injectable, UnauthorizedException } from '@nestjs/common';
import { PassportStrategy } from '@nestjs/passport';
import { ExtractJwt, Strategy, VerifiedCallback } from 'passport-jwt';
import { AuthService } from '../auth.service';
import { JwtPayloadWithRt } from '../types/jwtPayloadWithRt.type';
import { Payload } from '../types/payload.interface';
import { Request } from 'express';

@Injectable()
export class RtStrategy extends PassportStrategy(Strategy, 'jwt-refresh') {
  constructor(private configService: ConfigService) {
    super({
      // jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      jwtFromRequest: ExtractJwt.fromExtractors([
        (request) => {
          console.log('request?.cookies.jwt.rt : ', request?.cookies.jwt);
          return request?.cookies.jwt.refresh_token;
        },
      ]),
      secretOrKey: configService.get<string>('RT_SECRET'),
      passReqToCallback: true,
      // ignoreExpiration: false,
    });
  } // Generated by https://quicktype.io

  validate(req: Request, payload: Payload, done: VerifiedCallback): any {
    // const refreshToken = req?.get('authorization')?.replace('Bearer', '').trim();
    console.log('🚀 ~ file: rt.jwt.strategy.ts:31 ~ RtStrategy ~ validate ~ refreshToken');
    console.log('payload : ', payload);
    const refreshToken = req?.cookies?.jwt.refresh_token;

    if (!refreshToken) throw new ForbiddenException('Refresh token malformed');
    // return done(null);
    return {
      ...payload,
      refreshToken,
    };
  }
}
